#------lsd------#
alias l='lsd -1'
alias ls='lsd'
#alias lsd='lsd -d git'
alias ll='lsd -1'
alias la='lsd -a'
#alias ls='lsd --sd'
#alias lr='lsd -r'
alias tree='lsd --tree'
alias lgit='lsd --gs'
alias lgt='lsd --gs -t'
